In [1]:
# Create a tuple and add elements.
my_tuple = 1,2,3,"apple","mango","grapes"

In [2]:
# print the created tuple
print(my_tuple)

(1, 2, 3, 'apple', 'mango', 'grapes')


In [3]:
# create a numeric tuple.
tuple = 1,2,3,4,5,6,7,8,9

In [4]:
# print the min value from the numeric tuple.
min(tuple)

1

In [5]:
# Add first tuple and numeric tuple and named as r1.
r1 = my_tuple + tuple

In [6]:
# print the resulted tuple.
print(r1)

(1, 2, 3, 'apple', 'mango', 'grapes', 1, 2, 3, 4, 5, 6, 7, 8, 9)


In [7]:
# Create two sets
set1 = {1, 2, 3, 4, 5}
set2 = {2, 3, 7, 6, 1}

In [8]:
# Union of two sets.
Result = set1.union(set2)

In [9]:
print(Result)

{1, 2, 3, 4, 5, 6, 7}


In [10]:
# intersection of two sets.
Result1 = set1.intersection(set2)

In [11]:
print(Result1)

{1, 2, 3}


In [12]:
# difference of two tuples.
Result2 = set1.difference(set2)

In [13]:
print(Result2)

{4, 5}


In [14]:
# create a 3X3 matrix array with value  rangig from 2 to 10
import numpy as np
X =  np.arange(2, 11).reshape(3,3)
print(X)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


Create a numpy array having user input values and convert the integer type to the float type of the elements of the array.

In [15]:
import warnings
warnings.filterwarnings('ignore')
array1 = [1,2,3,4]

In [16]:
sampleArray = np.array(array1)

In [17]:
FloatArray = sampleArray.astype(np.float)

In [18]:
print(FloatArray)

[1. 2. 3. 4.]


Create numpy program to append values to the end of an array

In [19]:
import numpy as np
Array1 = [10, 20, 30]
print("Original array:", Array1)

Array1 = np.append(Array1, [[40, 50, 60], [70, 80, 90]])
print("After append values to the end of the array:", Array1)


Original array: [10, 20, 30]
After append values to the end of the array: [10 20 30 40 50 60 70 80 90]


Create two numpy arrays and add the elements of both the arrays and store the result  in sub-array

In [20]:
Array1 = np.array([1,2,3,4,5])

Array2 = np.array([6,7,8,9,10])

SubArray = np.add(Array1,Array2)

In [21]:
print(SubArray)

[ 7  9 11 13 15]
